### set up of the Jupyter Notebook
set up is done by the developer
of the underling python modules

In [5]:
import pandas as pd
import uuid
import json
from mstr_robotics import regam
from mstr_robotics._helper import msic
from mstr_robotics.mstr_classes import get_conn,md_searches
from mstr_robotics.report import prompts

run_id = uuid.uuid1().__str__()
i_test=regam.test_exe()
#i_parse_pa = parse_pa()
#i_dossiers=dossiers()
i_msic=msic()
i_prompts=prompts()
i_get_conn=get_conn
i_regam=regam.regam({"run_id": run_id})
i_md_search=md_searches()
i_regam_jobs=regam.regam_jobs()

with open('C:\\coding\\Python_environments\\mstr_robotics\\config\\user_d.json', 'r') as openfile:
    user_d = json.load(openfile)

#set user credentials and open a connection to the i-server

project_id="B7CA92F04B9FAE8D941C3E9B7E0CD754"
pa_project_id="7576CD5F48607C21C914ACBE053B259B"
#username = user_d["username"]
#password =user_d["password"]
#base_url= user_d["base_url"]


pa_base_url= user_d["conn_params"]["base_url"]

conn_params =  user_d["conn_params"]
conn_params["project_id"]=project_id
#conn = Connection(**conn_params)



conn=get_conn(**conn_params)
conn.select_project(project_id)
conn.headers['Content-type'] = "application/json"
           
pa_conn=get_conn(**conn_params)
pa_conn.select_project(pa_project_id)

Connection to Strategy One Intelligence Server has been established.
Connection to Strategy One Intelligence Server has been established.

In [11]:
#get the jobs stored in a static report for this use case.
pa_report_id="31FF880045D230BE04C209A42C108B24"
pa_conn.select_project(pa_project_id)
pa_raw_data_df=i_regam.fetch_pa_rep_jobs(pa_conn=pa_conn, pa_report_id=pa_report_id)
#identify projects and prompts
#pa_prp_id_l = i_parse_pa.get_pa_prp_id_l(get_pa_raw_data_df=pa_raw_data_df)
pa_raw_data_df

,Date@ID,Session@ID,Job@ID,Project@Name,Project@GUID,Object@Name,Object@GUID,Prompt_Type@DESC,Prompt_Type@ID,Prompt@Name,Prompt@GUID,Prompt_Answer@ID,Prompt_Answer_Sequence@ID,Sum Action CPU Duration (s)
0,11/22/2025,7397877267071766528,303,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,Customer Detail report (Dashboard),C060EF484E1352B26D945CBAF191F2B8,Attribute Element Prompt,2,Choose from the Elements of Customer,31A96A44479DBB67AA74B381CE8348DE,,1,0.0
1,11/22/2025,7397877267071766528,303,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,Customer Detail report (Dashboard),C060EF484E1352B26D945CBAF191F2B8,Attribute Element Prompt,2,Elements of Call Center,76A492374445A79DE945CD991068419C,,1,0.0
2,11/22/2025,7397877267071766528,303,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,Customer Detail report (Dashboard),C060EF484E1352B26D945CBAF191F2B8,Attribute Element Prompt,2,Elements of Customer Region,BE16BFE74B63506CA59FE3AA71174916,,1,0.0
3,11/22/2025,7397877267071766528,303,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,Customer Detail report (Dashboard),C060EF484E1352B26D945CBAF191F2B8,Attribute Element Prompt,2,Elements of Employee,EBCB12A0469E6FA5D49800B25B33E0D3,,1,0.0
4,11/22/2025,7397877267071766528,303,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,Customer Detail report (Dashboard),C060EF484E1352B26D945CBAF191F2B8,Attribute Element Prompt,2,Elements of Manager,7DA2E6DD4BF14BAFCCFDB7B5A38BE70E,,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,12/11/2025,7404932072055246848,17183,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,promptSample,C58A830B4DEB35BF601D119134952B83,Attribute Element Prompt,2,Choose from the Elements of Call Center,09CF58C14B38F7AD1F9CAFBEBEA60AC2,San Francisco,1,0.0
955,12/11/2025,7404932072055246848,17183,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,promptSample,C58A830B4DEB35BF601D119134952B83,Attribute Element Prompt,2,Choose one or more years,92974D7148B81A1AEDB5AFB7DC198F95,"2022,2020,2021",1,0.0
956,12/11/2025,7404932072055246848,17183,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,promptSample,C58A830B4DEB35BF601D119134952B83,Attribute Element Prompt,2,Select a Category,659E3A98429055ABE3DC448228E508CB,Books,1,0.0
957,12/11/2025,7404932072055246848,17183,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,promptSample,C58A830B4DEB35BF601D119134952B83,Object Prompt,24,Choose from a list of attributes,753C65EB402C44D3A991F285D3CB7F6D,Subcategory,1,0.0
958,12/11/2025,7404932072055246848,17183,MicroStrategy Tutorial,B7CA92F04B9FAE8D941C3E9B7E0CD754,promptSample,C58A830B4DEB35BF601D119134952B83,Prompt,28,Qualify on Time,78EB1EE14770755DA97A7891280DF4DD,"Month = Feb 2020, Jul 2020, Aug 2020",1,0.0

In [ ]:
#to parse attribute expresion prompts
#we need GUID. We can fetch this from the endpoint hierarchies
#the result bis stored in a cube
conn.select_project(project_id)
REGAM_cube_folder_id="C57AFAEC4DE90EE2DE84BC8155D32DE8"
hier_att_cube_id="DC78107F4DE830DF127FA592C1EB7E68 "
hier_att_df=i_regam.refresh_hier_att_cube(conn=conn,REGAM_cube_folder_id=REGAM_cube_folder_id,proj_prp_hier_l=None,
                      hier_att_cube_id=hier_att_cube_id)

WWWW [{'project_id': 'B7CA92F04B9FAE8D941C3E9B7E0CD754', 'id': 'FD107ADDE8A948AE80F794A288FA70F4', 'name': 'System Hierarchy', 'type': 14, 'subtype': 3584, 'dateCreated': '2010-06-11T18:38:55.000+0000', 'dateModified': '2025-11-27T11:41:21.000+0000', 'version': 'AAAADADE594DEA4CE73EBB8B7EFB8FA6', 'owner_id': '54F3D26011D2896560009A8E67019608', 'owner_name': 'Administrator'}]
     run_id                        project_id  \
0    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
1    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
2    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
3    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
4    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
5    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
6    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
7    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
8    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
9    run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
10   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
11   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
12   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
13   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
14   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
15   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
16   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
17   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
18   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
19   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
20   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
21   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
22   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
23   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
24   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
25   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
26   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
27   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
28   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
29   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
30   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
31   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
32   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
33   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
34   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
35   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
36   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
37   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
38   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
39   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
40   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
41   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
42   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
43   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
44   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
45   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
46   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
47   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
48   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
49   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
50   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
51   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
52   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
53   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
54   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
55   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
56   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
57   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
58   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
59   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
60   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
61   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
62   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
63   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
64   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
65   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
66   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
67   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
68   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
69   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
70   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
71   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
72   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
73   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
74   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
75   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
76   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
77   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
78   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
79   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
80   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
81   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
82   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
83   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
84   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
85   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
86   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
87   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
88   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
89   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
90   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
91   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
92   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
93   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
94   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
95   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
96   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
97   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
98   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
99   run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
100  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
101  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
102  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
103  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
104  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
105  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
106  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
107  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
108  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
109  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
110  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
111  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
112  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
113  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
114  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
115  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
116  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
117  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
118  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
119  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
120  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
121  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
122  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
123  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
124  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
125  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
126  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
127  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
128  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
129  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
130  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
131  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
132  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
133  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
134  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
135  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
136  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
137  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
138  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
139  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
140  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
141  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
142  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
143  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
144  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
145  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
146  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
147  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
148  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
149  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
150  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
151  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
152  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
153  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
154  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
155  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
156  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
157  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
158  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
159  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
160  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
161  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
162  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
163  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
164  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
165  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
166  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
167  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
168  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
169  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
170  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
171  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
172  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
173  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
174  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
175  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
176  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
177  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
178  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
179  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
180  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
181  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
182  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
183  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
184  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
185  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
186  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
187  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
188  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
189  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
190  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
191  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
192  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
193  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
194  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
195  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
196  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
197  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
198  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
199  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
200  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
201  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754
202  run_id  B7CA92F04B9FAE8D941C3E9B7E0CD754

                              hier_id  hier_subType         hier_name  \
0    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
1    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
2    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
3    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
4    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
5    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
6    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
7    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
8    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
9    FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
10   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
11   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
12   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
13   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
14   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
15   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
16   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
17   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
18   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
19   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
20   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
21   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
22   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
23   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
24   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
25   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
26   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
27   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
28   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
29   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
30   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
31   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
32   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
33   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
34   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
35   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
36   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
37   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
38   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
39   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
40   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
41   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
42   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
43   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
44   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
45   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
46   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
47   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
48   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
49   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
50   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
51   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
52   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
53   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
54   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
55   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
56   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
57   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
58   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
59   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
60   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
61   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
62   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
63   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
64   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
65   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
66   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
67   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
68   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
69   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
70   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
71   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
72   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
73   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
74   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
75   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
76   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
77   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
78   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
79   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
80   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
81   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
82   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
83   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
84   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
85   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
86   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
87   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
88   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
89   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
90   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
91   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
92   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
93   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
94   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
95   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
96   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
97   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
98   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
99   FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
100  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
101  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
102  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
103  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
104  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
105  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
106  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
107  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
108  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
109  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
110  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
111  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
112  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
113  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
114  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
115  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
116  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
117  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
118  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
119  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
120  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
121  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
122  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
123  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
124  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
125  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
126  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
127  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
128  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
129  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
130  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
131  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
132  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
133  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
134  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
135  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
136  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
137  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
138  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
139  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
140  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
141  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
142  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
143  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy
144  FD107ADDE8A948AE80F794A288FA70F4          3584  System Hierarchy

Uploading 1/1:   0%|          | 0/1 [00:00<?, ?it/s]

Error uploading data to dataset DC78107F4DE830DF127FA592C1EB7E68
Could not decode the response from the I-Server. Please check if I-Server is running correctly

Uploading 1/1: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s, rows=203]

Error publishing uploaded data for dataset with ID DC78107F4DE830DF127FA592C1EB7E68 Cancelling publication.
Could not decode the response from the I-Server. Please check if I-Server is running correctly

Super cube 'System hier_att' published successfully.

### Define your environment
I prefer config files, but you also can write the GUID directly.

In [ ]:
conn.select_project(project_id)
test_project_d=i_msic.get_dict_with_id_in_l(dict_l= MSTR_robotics_config_d["REGAM_project"],search_l=[project_id],
                             key="project_id")[0]

#hier_att_cube_id =  test_project_d["hier_att_cube_id"]

REGAM_log_file= "C:\\coding\\python_io\\output_files\\log\\REGAM_logs.txt"
pa_report_id="31FF880045D230BE04C209A42C108B24"

### define the the test
prepare some masterdata
generate the prompt answers JSONs for re-play

In [ ]:
#search for all Dossiers under the REGAM folder
dossier_l=[]
regam_folder_id="65984E814DA3C4721FF4E3B83DDF4F4F"
search_dossier_l=i_md_search.search_for_type_l( conn=pa_conn, input_type="type_l", obj_l="55",root_folder_id=regam_folder_id)
for doss in search_dossier_l:
    dossier_l.append(doss["id"])
print(dossier_l)
#parse the structure of a dossier to and display chapter, pages & visualizations
doss_viz_df=i_dossiers.doss_hier_to_df(conn=pa_conn,dossier_l=dossier_l)
doss_viz_df

In [ ]:
filtered_df = doss_viz_df[doss_viz_df['visual_key']=="W65"]
#filtered_df = filtered_df[filtered_df['dossier_id']=="5F33A34742F786821D57019B32EF60D7"]
filtered_df

In [7]:
att_exp_ans_l=i_regam_jobs.run_read_out_job_vis(conn=pa_conn,filtered_df=filtered_df)
prompt_id="948E03AF475DF4E4B37BF8B404FB4D80"
prp_d=i_prompts.bld_expr_prp_answ(prompt_id, att_exp_ans_l)
prompt_answ=i_prompts.frame_prp(prp_ans=[prp_d])
pa_conn.select_project(pa_project_id)
pa_raw_data_df=i_regam.fetch_pa_rep_jobs(pa_conn=pa_conn, pa_report_id=pa_report_id,prompt_answ=prompt_answ)

NameError: name 'filtered_df' is not defined

In [ ]:
search_dossier_l

Empty DataFrame
Columns: [Date@ID, Session@ID, Job@ID, Project@Name, Project@GUID, Object@Name, Object@GUID, Prompt_Type@DESC, Prompt_Type@ID, Prompt@Name, Prompt@GUID, Prompt_Answer@ID, Prompt_Answer_Sequence@ID, Sum Action CPU Duration (s)]
Index: []

In [ ]:
hier_att_cube_id

In [ ]:
#load the cube hierarchy / Attribute information into a dataframe 
hier_att_df=i_regam.load_hier_att_df(conn=conn,hier_att_cube_id=hier_att_cube_id)
hier_att_df

In [ ]:
pa_raw_data_df=i_regam.fetch_pa_rep_jobs(pa_conn=pa_conn,  pa_report_id=pa_report_id)
pa_raw_data_df

In [ ]:
all_jobs_prp_ans_JSON_d=i_regam.run_bld_job_prp_JSON(conn,pa_raw_data_df=pa_raw_data_df,hier_att_df=hier_att_df)
all_jobs_prp_ans_JSON_d

### run the test

In [ ]:
i_test.run_test_exe(conn=conn,all_jobs_prp_ans_JSON_l=all_jobs_prp_ans_JSON_d["all_jobs_prp_ans_JSON_l"])

In [ ]:
REGAM_log_file

In [ ]:
hier_att_df

In [ ]:
pa_raw_data_df